/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "pch.h"
#include "variant_constants.h"

namespace variant {

const variantConstants g_variant_constants;

variantConstants::variantConstants() {
}

} // namespace

