/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef variant_CONSTANTS_H
#define variant_CONSTANTS_H

#include "variant_types.h"

namespace variant {

class variantConstants {
 public:
  variantConstants();

};

extern const variantConstants g_variant_constants;

} // namespace

#endif
